version: 2
executorType: machine
jobs:
  build:
    machine: true
    environment:
      SBT_OPTS: -Xmx3G -Xss6M
    steps:
      - checkout
      - restore_cache:
          keys:
            - sbt-cache-{{ checksum "build.sbt" }}
            - sbt-cache-
      - run: sbt scalafmtCheck scalafmtSbtCheck test:scalafmtCheck clean test coverage
      - save_cache:
          paths:
            - ~/.m2
            - ~/.ivy2/cache
            - ~/.sbt
          key: sbt-cache-{{ checksum "build.sbt" }}


  release:
    machine: true
    environment:
      SBT_OPTS: -Xmx3G -Xss6M
    steps:
      - checkout
      - restore_cache:
          keys:
            - sbt-cache-{{ checksum "build.sbt" }}
            - sbt-cache-
      - run: sbt scalafmtCheck scalafmtSbtCheck test:scalafmtCheck clean test coverageOff +releaseEarly


workflows:
  version: 2
  build:
    jobs:
      - build:
          context: jfrog
          filters:
            tags:
              ignore: /.*/
  release:
    jobs:
      - release:
          context: jfrog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
