addSbtPlugin("com.typesafe.sbt" % "sbt-git"             % "1.0.2")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"        % "2.4.0")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"       % "1.6.1")
addSbtPlugin("com.codacy"       % "sbt-codacy-coverage" % "3.0.3")
addSbtPlugin("ch.epfl.scala"    % "sbt-release-early"   % "2.1.1")
