addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager"  % "1.6.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-git"              % "1.0.0")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"         % "2.3.2")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.2")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"        % "1.6.1")
addSbtPlugin("com.codacy"       % "sbt-codacy-coverage"  % "3.0.3")
addSbtPlugin("com.eed3si9n"     % "sbt-assembly"         % "0.14.10")
